# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'AlarmofireDemo' do
pod 'Alamofire'
pod 'SwiftyJSON'
end

target 'AlarmofireDemoTests' do
pod 'Alamofire'
pod 'SwiftyJSON'
end

target 'AlarmofireDemoUITests' do
pod 'Alamofire'
pod 'SwiftyJSON'
end

